package galois

// Standard transitive permutation groups for degrees 3, 4, 5.

// TransitiveGroups3 returns the 2 transitive groups of degree 3.
func StandardS3() *PermGroup {
	g, _ := NewPermGroup("S3", 3, []Permutation{
		{1, 0, 2},    // (0 1)
		{1, 2, 0},    // (0 1 2)
	})
	return g
}

func StandardA3() *PermGroup {
	g, _ := NewPermGroup("A3", 3, []Permutation{
		{1, 2, 0},    // (0 1 2)
	})
	return g
}

// TransitiveGroups4 returns the 5 transitive groups of degree 4.
func StandardS4() *PermGroup {
	g, _ := NewPermGroup("S4", 4, []Permutation{
		{1, 0, 2, 3}, // (0 1)
		{1, 2, 3, 0}, // (0 1 2 3)
	})
	return g
}

func StandardA4() *PermGroup {
	g, _ := NewPermGroup("A4", 4, []Permutation{
		{1, 2, 0, 3}, // (0 1 2)
		{0, 2, 3, 1}, // (1 2 3)
	})
	return g
}

func StandardD4() *PermGroup {
	g, _ := NewPermGroup("D4", 4, []Permutation{
		{1, 2, 3, 0}, // r = (0 1 2 3)
		{3, 2, 1, 0}, // s = (0 3)(1 2)
	})
	return g
}

func StandardV4() *PermGroup {
	g, _ := NewPermGroup("V4", 4, []Permutation{
		{1, 0, 3, 2}, // (0 1)(2 3)
		{2, 3, 0, 1}, // (0 2)(1 3)
	})
	return g
}

func StandardC4() *PermGroup {
	g, _ := NewPermGroup("C4", 4, []Permutation{
		{1, 2, 3, 0}, // (0 1 2 3)
	})
	return g
}

// TransitiveGroups5 returns the 5 transitive groups of degree 5.
func StandardS5() *PermGroup {
	g, _ := NewPermGroup("S5", 5, []Permutation{
		{1, 0, 2, 3, 4}, // (0 1)
		{1, 2, 3, 4, 0}, // (0 1 2 3 4)
	})
	return g
}

func StandardA5() *PermGroup {
	g, _ := NewPermGroup("A5", 5, []Permutation{
		{1, 2, 0, 3, 4}, // (0 1 2)
		{0, 1, 3, 4, 2}, // (2 3 4)
	})
	return g
}

// StandardF20 returns the Frobenius group F_20 (AGL(1, 5)) of order 20.
// Generated by x -> x + 1 mod 5 and x -> 2x mod 5.
func StandardF20() *PermGroup {
	// (0 1 2 3 4)
	trans := Permutation{1, 2, 3, 4, 0}
	// x -> 2x mod 5: 0->0, 1->2, 2->4, 3->1, 4->3: (1 2 4 3)
	mult := Permutation{0, 2, 4, 1, 3}
	g, _ := NewPermGroup("F20", 5, []Permutation{trans, mult})
	return g
}

// StandardD5 returns the Dihedral group D_5 of order 10.
// Generated by rotation (0 1 2 3 4) and reflection x -> -x mod 5.
func StandardD5() *PermGroup {
	// r = (0 1 2 3 4)
	r := Permutation{1, 2, 3, 4, 0}
	// s = x -> -x mod 5: 0->0, 1->4, 2->3, 3->2, 4->1: (1 4)(2 3)
	s := Permutation{0, 4, 3, 2, 1}
	g, _ := NewPermGroup("D5", 5, []Permutation{r, s})
	return g
}

// StandardC5 returns the Cyclic group C_5 of order 5.
func StandardC5() *PermGroup {
	r := Permutation{1, 2, 3, 4, 0}
	g, _ := NewPermGroup("C5", 5, []Permutation{r})
	return g
}
